---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: yarn
      # - run: chown -R $USER:$USER /root/cli
      # - run: ./bin/run --version
      # - run: ./bin/run --help
      # - run:
      #     name: Testing
      #     command: npm test
      - run:
          name: Testing
          command: npm run test:dev
      # - run:
      #     name: Submitting code coverage to codecov
      #     command: |
      #       ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
      #       curl -s https://codecov.io/bash | bash
  cache:
    <<: *test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
          paths:
            - ~/cli/node_modules
            - ~/.npm
            - /usr/local/lib/node_modules

workflows:
  version: 2
  "job-o-scraper":
    jobs:
      - node-latest
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
